
	<h1>Reports <?php if ($this->success) { ?><span id="alert"><?php echo $this->success ?></span><?php } ?></h1>

	Coming soon..
	
	<div id="top-actions" class="actions">
<!--
		<input type="submit" value="Create an offer" onclick="showForm('new-offer')"/>
		<input type="submit" value="Edit checked" disabled />
		<input type="submit" value="Disable checked" disabled />
		<input type="submit" value="Enable checked" disabled />
-->
	</div><!-- /#top-actions -->